CREATE TABLE [nan].[AgencyDetails] (
    [AgencyDetailsId]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [AgencyDetailsName]      NVARCHAR (60)  NULL,
    [Address1]               NVARCHAR (250) NULL,
    [Address2]               NVARCHAR (250) NULL,
    [GoogleLat]              NVARCHAR (20)  NULL,
    [GoogleLong]             NVARCHAR (20)  NULL,
    [AreaId]                 BIGINT         NULL,
    [PostCode]               NVARCHAR (20)  NULL,
    [Phone]                  NVARCHAR (20)  NULL,
    [Email]                  NVARCHAR (100) NULL,
    [Website]                NVARCHAR (100) NULL,
    [ContactForm]            NVARCHAR (100) NULL,
    [IsProfileReviewed]      BIT            NULL,
    [IsDeleteProfile]        BIT            NULL,
    [DeleteProfileDateTime]  DATETIME       NULL,
    [IsActiveProfilebyAdmin] BIT            NULL,
    [IsActiveProfile]        BIT            NULL,
    [ActiveProfileDateTime]  DATETIME       NULL,
    [CheckedTerms]           BIT            NULL,
    [IsSubscribeNewsletter]  BIT            NULL,
    [LastLoginTime]          DATETIME       NULL,
    [CreatedOn]              DATETIME       CONSTRAINT [DF_AgencyDetails_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              BIGINT         NOT NULL,
    [UpdatedOn]              DATETIME       NULL,
    [UpdatedBy]              BIGINT         NULL,
    [DeletedOn]              DATETIME       NULL,
    [DeletedBy]              BIGINT         NULL,
    [IsDeleted]              BIT            CONSTRAINT [DF_AgencyDetails_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_AgencyDetails] PRIMARY KEY CLUSTERED ([AgencyDetailsId] ASC),
    CONSTRAINT [FK_AgencyDetails_AreaMaster] FOREIGN KEY ([AreaId]) REFERENCES [nan].[AreaMaster] ([AreaMasterId])
);

